# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=-99),
            preserve_default=False,
        ),
    ]
